### ISSUE TITLE
Hueサンプル追加の提案

### ISSUE THREAD

**Issue by hidessy** [w3c/wot-jp-cg#28]
現在、Raspberry PiでのLED,気圧,温湿度のサンプルがあり、今後コンテンツの拡充に向けて、既存のAPIのあるデバイスをWoT化する例として、Hueのサンプルを追加したいと考えています。
内容やツールに関しては、WoTify(https://wotify.org/ )にありますThing Descriptionを元に、Node-REDからnode-red-nodegenを使って、既存のサンプルと同様にまとめていきたいと思います。
また、それに伴い例の項目の構成を下記のように分けたいと考えています。

>   - 例
>     - Raspberry Pi
>       - 気圧センサー BMP280
>       - 温湿度センサー SHT3x
>     - スマート家電（APIの利用）
>       - Hue ブリッジ
>       - Hue 電球 ホワイトグラデーション

コンテンツ拡充のサンプルやデバイス、ツールなど、何かございましたらコメントいただけますと幸いです。
問題なければ今後、サンプルの作成やPull Requestとしての提案を進めていきたいと思います。
よろしくお願いいたします。

**Comment by hidessy** [comment]
#30 にてHue 電球 ホワイトグラデーションの提案をさせていただきました。

**Comment by dynamis** [comment]
> Hue 電球 ホワイトグラデーションの提案をさせていただきました。

最初に書かれた目次例としては「Hue ブリッジ」もありましたが、そちらまたは他の Hue デバイスも題材にしたサンプル追加は検討/予定されていますか？ (といった方針の情報も随時展開頂ければ幸い)

**Comment by k-toumura** [comment]
#30 をマージしました。
他のHueデバイスに関するサンプル追加が予定されているかがまだ明確ではないので、このissueはopenのままにしておきます。

**Comment by dynamis** [comment]
> 他のHueデバイスに関するサンプル追加が予定されているかがまだ明確ではないので、このissueはopenのままにしておきます。

Wotify サイトあるいは元となる https://github.com/tum-esi/wot-sys に TD があるものとしてはは Bridge, Dimmer Switch, Daylight Sensor というのもあるが、Bridge だけでは面白くない、Daylight Sensor はどの商品か不明＆日本で合法で使えるか未確認ということで、扱うなら Dimmer Switch くらいかなという話をしました。

https://www.philips-hue.com/ja-jp/p/hue-dimmer-switch/8718696752029

とはいえ Hue だけ説明一杯書いても仕方ないので、他プラットフォームのサンプル追加を優先した方が良いかもと考えています(WoT の真価はプラットフォーム横断のハズなので個々のプラットフォームに力を入れすぎる必要はないはず。具体的には myCobot 280 ですが、それ以外も実現可能＆組み合わせて見せて面白いものがないか検討中)。

Hue については、こっちの TD とか見えれば Dimmer Switch もつかるよと簡単に補足を追加する程度で良いかなと思っているところですが、如何でしょうか？皆様のご意見募集です。

**Comment by k-toumura** [comment]
> Hue については、こっちの TD とか見えれば Dimmer Switch もつかるよと簡単に補足を追加する程度で良いかなと思っているところですが、如何でしょうか？皆様のご意見募集です。

はい。基本がわかればあとは補足で参考になるサイトのpointerを示すのでよいと思います。
特に問題がなければ、一旦このissueはcloseしておこうと思います。
