### ISSUE TITLE
CG 活動の提案・承認/却下フローを決めて明文化したい

### ISSUE THREAD

**Issue by dynamis** [w3c/wot-jp-cg#29]
WoT-JP CG として 4 つの TF を設立して活動を始める (引き継ぎ継続する) ことになりましたが、コミュニティとしてオープンに進行をする上で議論の進め方や決定フロー、モデレータなどを明文化しておいた方が良いのではないでしょうか。

叩き台としてドラフトを書いてみますが、皆様如何でしょうか？

- CG の取り組みは原則 issue, PR または meeting にて提案・合意の上で進める
  - repo 中の code/docs/translation などの変更は issue/PR いずれで開始しても良い
  - コード変更以外の活動・議論などは issue にて行う
  - typo や docs 書き足しなど軽微な修正はコミット権限を持つ人は直接 main コミットしてもよい
  - meeting では即時合意・決定ができる (合意内容は簡単にでもログを残すのが望ましい)
- 提案に対する承認/却下の合意プロセスは次の通り
  - TF リーダーと指名メンバーをモデレータとする (README に記載)
  - 他メンバーから賛成のみの場合、モデレータの決定または提案から 2 weeks 経過時点で承認
  - 他メンバーから賛否がある場合、モデレータが決定する (それまで判断保留)
  - 他メンバーからの反応がない場合は保留
  - 提案に対する賛否はコメントリプライは勿論、単に良いねボタンで表しても良い
- 以上 CG 全体の共通プロセスとして README か Wiki に記載する
  - TF 毎の判断でプロセスの調整は可能だがその場合は issue で議論の上で決めて README に記載する

**Comment by dynamis** [comment]
> - 他メンバーから賛否がある場合、モデレータが決定する

この点は W3C の運営は全体的にコンセンサスを取って進めるというのが原則だろうというコメントを頂きましたので、

- 他メンバーから賛否がある場合、参加者とのコンセンサスを取りつつモデレータが決定する

> - 提案に対する賛否はコメントリプライは勿論、単に良いねボタンで表しても良い

この点はコメントを書く人とボタンを押すだけの人手は重みが明らかに違うだろう、とか、曖昧な賛否の表現となることもあるので

- 提案に対する賛否は原則コメントリプライにて表明する
  - 良いね (+1)、ハート (heart) については賛意を表すことにも利用できる
  - 反対の場合は良くないね (-1) ボタンだけではなくコメントで表明すること

**Comment by dynamis** [comment]
label は policy と 4 つの各 TF 名のものを作成した。

meeting の議論の結果として以下を policy.md にまとめようと思います:

- CG の取り組みは原則 issue, PR または meeting にて提案・合意の上で進める
  - repo 中の code/docs/translation などの変更は issue/PR いずれで開始しても良い
  - コード変更以外の活動・議論などは issue にて行う
  - typo や docs 書き足しなど軽微な修正はコミット権限を持つ人は直接 main コミットしてもよい
  - meeting では即時合意・決定ができる (合意内容は簡単にでもログを残すのが望ましい)
- 提案に対する承認/却下の合意プロセスは次の通り
  - TF リーダーを各 TF に関する issue, PR のモデレータとする
    - TF リーダーは、代理モデレータを指名しモデレート権限を与えることができる (README に記載)
  - 他メンバーから賛成のみの場合、モデレータの決定または提案から 2 weeks 経過時点で承認とする
  - 他メンバーから賛否がある場合、モデレータが決定する (それまで判断保留)
  - 他メンバーからの反応がない場合は保留する
- 提案に対する賛否は原則コメントリプライにて表明する
  - 良いね (+1)、ハート (heart) については賛意を表すことにも利用できる
  - 反対の場合は良くないね (-1) ボタンだけではなくコメントで表明すること
- 各 TF 活動に関する issue, PR を立てるときは TF 名のラベルを付ける
  - レビューすべき人が明らかな場合は assignee や reviewer の指名も
- 以上 CG 全体の共通プロセスとして README か Wiki に記載する
  - TF 毎の判断でプロセスの調整は可能だがその場合は issue で議論の上で決めて README に記載する

**Comment by dynamis** [comment]
ここまででまとまったモノを (冒頭文の追加・表記の整理や明確化をした上で) PR #32 としてマージしました。
皆さんの確認を経て、問題無ければ Draft という表記を外して確定としたいと思います (現状 Draft です)。

https://github.com/w3c/wot-jp-cg/blob/main/POLICY.md

**Comment by k-toumura** [comment]
> 提案者以外の参加者が賛成のみの場合、モデレータが決裁するか提案から 2 週間経過した時点で承認とする

#30 に関しては念のため2週間待って承認としましたが、「モデレータが決裁する」場合には
どれだけ待ってから「賛成のみ」という判定をすればよいのかが難しいですね。

**Comment by dynamis** [comment]
> #30 に関しては念のため2週間待って承認としましたが、「モデレータが決裁する」場合には
どれだけ待ってから「賛成のみ」という判定をすればよいのかが難しいですね。

meeting での合意では即時決裁を可能としたように、ルール化することで速度が落ちるのは良くないとも思っています。反対がでなさそうなモノ、一旦入れても問題あれば後で再度修正可能なコミット (ドキュメントやコードの殆どはこれに該当) であればモデレータが早期に GO する運用を想定していました (2 週間と書いたのはモデレータ決裁ない場合でも放置が最長 2 週間とするためのもので、デフォルト 2 週間という意図ではなかった)。

その辺りの意図は現状だけでは汲み取れないですね...

**Comment by dynamis** [comment]
...ということで他のモデレータの皆さんとも meeting で議論してこのように改訂してみましたが如何でしょうか > @k-toumura 

https://github.com/w3c/wot-jp-cg/commit/ea2c547057a5b574f4c96a9805e25544624fd330
> 提案者以外の参加者が賛成のみの場合、提案の粒度と内容に応じ提案から 2 週間以内の適切な期間でモデレータが決裁した時点で承認とする

**Comment by k-toumura** [comment]
> ...ということで他のモデレータの皆さんとも meeting で議論してこのように改訂してみましたが如何でしょうか > @k-toumura

ありがとうございます。これで問題ないと思います。

**Comment by dynamis** [comment]
こちらにて案は確定、ML で全体にアナウンスの上で "(Draft)" を外して確定ということで。

**Comment by dynamis** [comment]
ML アナウンスされていなかったが明日の WoT JP CG キックオフイベントでの説明を持って確定とする
