### ISSUE TITLE
Outreach活動の進め方について

### ISSUE THREAD

**Issue by dajiaji** [w3c/wot-jp-cg#31]
Outreach TFとして、これから複数のイベントを企画・実施していきたいと考えています。

浅井さんがまとめてくださったgithubのIssueベースで進める全体方針を踏襲しつつ、Github Projectsを使ってイベントの候補リストの管理、企画・実施の進捗管理を行うのはどうかと考えているのですが、如何でしょうか？

以下、素案です。

- Project名：Outreach活動
- カラム構成：
    - 候補リスト
        - 現状候補に挙がっているもの、今後CG会合で出して頂くものはとりあえずここに入る。
        - 個別の項目(Issue)の中で、実施するか否かを議論する。実施する場合には担当者を明にアサインする。
    - 実施予定（To Do）
        - 実施すると決定されたものは一旦、このカラムに入る。
    - 実施準備中 (In Progress)
        - スケジュール・内容の詳細化、参加者の募集など具体的な準備段階に入ったら、このカラム内で管理。
    - 実施済 (Done)
        - イベントが実施され、実施後のレポートをIssue中に記載したらDone。
- その他
    - イベント案の登録用テンプレートも用意する。
        - タイトル、概要、目的、想定参加者、実施時期など

 
【参考】アウトリーチTF   READMEより：
https://github.com/w3c/wot-jp-cg/tree/main/TF/Outreach
> ## 取り組み方針・手順
> 啓蒙活動（ウェビナー・勉強会・アイデアソン・ハッカソン）、他標準化活度とのリエゾン活動（交流会）の候補をリストアップし、本TFの活動の候補リストとして管理する。
> すでに挙がっているアイデア（下記「活動の候補リスト」）に加え、随時CG参加メンバから意見収集できる枠組みも合わせて作る。
> 本TFにて、上記リストから実施可能なものをピックアップし、担当をアサインの上、企画・実施する。
> 実施後に、内部的な報告会を開催し（あるいは報告レポートを作成し）、他TFへ情報共有を行う。
> 例えば、ユースケースや要件をユースケースTFにインプットするなど

**Comment by dynamis** [comment]
イベントやミーティングなどの締切が明確だが色んな人が関わってくるモノについては進行ステータスが分かり易くなるので Outreach 用の Projects を立てて進めるのはアリだと思います。

**Comment by dajiaji** [comment]
Issue上で東村さん、浅井さんから賛意をいただいたのと、前回の定例で芦村さんにもポジティブな意見を頂いたので、とりあえずProject化させて頂く方向で進めさせていただきます。（最終決定は本日11/16の定例にて）

**Comment by dynamis** [comment]
note (関連リンク):
- プロジェクトが作られた: https://github.com/w3c/wot-jp-cg/projects/1
- issue テンプレも PR が作られた https://github.com/w3c/wot-jp-cg/pull/33

**Comment by dynamis** [comment]
link: Outreach TF の README にも説明が記載されたし、既に 3 イベントの提案が本フローに従って企画提案されている:

- #34
- #44
- #45 

Outreach 活動の進め方・進捗管理/可視化の方法を決めるという本 issue の役割は完了したとしてクローズしても良いかも？

**Comment by dajiaji** [comment]
ありがとうございます。そうですね。クローズさせて頂きます。
