### ISSUE TITLE
myCobot 280(Python APIのWoT化)サンプル追加の提案

### ISSUE THREAD

**Issue by hidessy** [w3c/wot-jp-cg#35]
先日、既存のAPIのあるデバイスをWoT化する例として、Hue White Lightのサンプルを追加させていただきました。
次に、Python APIをWoT 化する例として、[myCobot 280](https://www.elephantrobotics.com/en/mycobot-en/)を用いたサンプルを追加したいと考えています。 

Python APIをWoT 化するためのツールやライブラリに関してですが、WebThings Librariesの[webthing-python](https://github.com/WebThingsIO/webthing-python)や、WoTランタイム実装として[WoTPy](https://github.com/agmangas/wot-py)が使えるのではないかと考えています。 
一方で、WebThings(旧Mozilla WebThings)ですが、[W3C仕様と異なる箇所](https://github.com/webthingsio/wiki/wiki/Mozilla-W3C-Differences)もございます。
そこで、サンプルとしては、WoT仕様に従ったWoTPyを使用してサンプルの説明を進めていくとともに、webthing-pythonについては言及にとどめておくか、軽い説明を書いていきたいと思います。

Python APIのWoT化するためのライブラリやツール、説明の進め方など何かございましたらコメントをいただけますと幸いです。
問題なければ今後、サンプルの作成やPull Requestとしての提案を進めていきたいと思います。
よろしくお願いいたします。

**Comment by k-toumura** [comment]
提案ありがとうございます。

Python APIは[これ](https://www.elephantrobotics.com/docs/myCobot-en/3-development/3-python/3.1-api.html)でしょうか。MDIモードでの操作をpropertyとして抽象化、JOGモードでの操作をactionとして抽象化するとちょうどproperty, actionの説明にちょうどいいのかもしれません。

また、PlugfestなどでもWoTPyを使っている例をあまり見かけないので、このサンプルで使い方がわかると個人的にもうれしいです。

Thingだけでなく、Consumerのサンプルも作って何らかの意味のある動きができるとさらに面白いと思いますが、ちょっと大変でしょうか?

**Comment by dynamis** [comment]
> Thingだけでなく、Consumerのサンプルも作って何らかの意味のある動きができるとさらに面白い

ですね。Consumer含めて定義していけないかとか、WoTなのだから個別機材の操作をWoT化するのに閉じず、複数プラットフォーム間の連携を図ることを含めて自然とWoTの役割や範囲が分かるようにサンプル作り、デモなどまでして行ければベストだが果たしてどんな使い方や連携が面白いか悩ましいねと言いつつまずはここからと作ってるのが現状なので、どんな Consumer 面白いかなどのゴイケンゴヨウボウモ募集中です！

> PlugfestなどでもWoTPyを使っている例をあまり見かけない

サンプルとして貴重なら英語圏にも発信していきたいですねぇ。

因みに plugfest では WoTPy 使わないと言いますが逆に何を使われるのでしょう？plugfest のこれもサンプルとして紹介すると良いとか良くある実装パターンとかがあるならそれも何らかの形でま整理したり言及したりしたいところです。

(少しissueから脱線してますが全体の流れとその中での位置づけ含めて検討しつつの提案なので)

**Comment by k-toumura** [comment]
> 因みに plugfest では WoTPy 使わないと言いますが逆に何を使われるのでしょう？

標準化メンバが多数かかわっている[node-wot](https://github.com/eclipse/thingweb.node-wot/)ベースのものが多いようにみえます。WoT Scripting-APIの事実上のリファレンス実装といってよいかと。

**Comment by dynamis** [comment]
やはり基本 node-wot ですかぁ。node-wot ばかりだと Web だからって JS (やhttp)メインで他がおざなり感が出てしまいそうな気がするので python とか他のライブラリや実例もあるよって見せていきたい、そういう意味でこの例は良いはず！

**Comment by chachamimm** [comment]
node-wotはWoT WG/IGのScripting APIのTFで検討されていた関係もあるし、できるかぎり検討中の機能も実装されているのでPlugFestでは使いやすくなってます。一方、WoTPyは使ってないというか、使う人がいないという感じですね。

ただ、node-wot、WoTPyについてどこかにチュートリアルを書いておくべきかなと思います。ただ、真面目に追いかけると、更新があるので、少し面倒かもしれません。

**Comment by dynamis** [comment]
> できるかぎり検討中の機能も実装されているのでPlugFestでは使いやすくなってます

そうですよね、仕様自体がまだまだ変わる・追加される中で追従して実装しているのは node-wot だけという状態ですものね。実際実用化されていくときに node だけでは

> node-wot、WoTPyについてどこかにチュートリアルを書いておくべきかなと思います。

(どういう仕様があるのかという話と共に) どういうライブラリがあるかという簡単な紹介はしないとなと考えているのですが、ライブラリの使い方について何処まで踏み込むものを (公式の説明の他に) 用意するのかは迷いがある状況です。取りあえず少しずつコンテンツの追加をしていく中でまたツッコミご意見お願いします。

**Comment by hidessy** [comment]
遅くなりましたが、先ほど #40 にてロボットアーム myCobot 280の提案をさせていただきました。
[Python API](https://github.com/elephantrobotics/pymycobot/tree/main/docs) を用いて、Property でサーボモータの角度の取得（`get_angles()`）、Action でサーボモータの操作（`send_angles(degrees, speed)`, `release_all_servos()`）を行なっています。

Consumerのサンプルについてですが、今後、複数の機器を連携したデモの実装を進めていく際に、合わせて考えていきたいと思います。

よろしくお願いいたします。

**Comment by dynamis** [comment]
[デプロイプレビュー](https://deploy-preview-40--wot-jp-cg.netlify.app/#/examples/mycobot/) で読んでみて、概ね良いと思うのですが細かなところでコメントです:

- 語尾「ございます」はチュートリアルの文章としてはダメじゃないけど、他ページとの統一感としては少し違和感あり。「」
- nosec などの値は `nosec` のようにコードとして強調しておいた方が良い
- 「Property, Action の定義を行ないます」とか「 action を "boolean" で定義します。」コード中では `properties` や `actions` しか登場しておらず単数 `action` は存在しないが説明分では単数のものが見受けられる。コードの一部を指すなら単複も揃えるべきだが、多分コードの引用・参照ではなく用語として表記している感じですね。それなら「プロパティ」とか「アクション」とかカタカナ表記(翻訳)する方が読みやすいのではないかと。
  - 既存のページの文章でも「プロパティ」や「アクション」になっているのが多い印象なので統一という点でも。

**Comment by k-toumura** [comment]
PRありがとうございます。PRとissueのどちらにコメントしようか迷いましたが、こちらで議論が進んでいるのでこちらにコメントします。

- myCobotの写真や、使用例のところに実際にcurlコマンドで動かしているところの動画があるとイメージが掴みやすいとおもいます。もし撮影できそうであれば是非お願いします。
- [サンプルコード](https://github.com/hidessy/wot-examples/blob/main/mycobot/mycobot.py)もw3c/wot-jp-cg内においた方が良いでしょうか? 皆様のご意見をお聞かせください。

**Comment by dynamis** [comment]
comment by 芦村さん:
> API そのままの例だけではなく「右で掴んで左に持って行って話す」といった実用的な使い方に合わせたサンプルコードも欲しい。

これについては一旦マージした後でも、デモを作った後に実コードサンプルを追加すれば良いかと思いました。

**Comment by dynamis** [comment]
> 使用例のところに実際にcurlコマンドで動かしているところの動画があるとイメージが掴みやすいとおもいます。もし撮影できそうであれば是非お願いします。

動画は撮っていたと思いますし、全部じゃないにしても 1-2 つは何処かに動画を入れてイメージ伝わる感じにしましょう。これは現状の curl コマンド一つだけのものでもいいし、後日いくつかのコマンドを連続して叩いたデモっぽいものにを追加するのもアリだと思います > @hidessy 

> サンプルコードもw3c/wot-jp-cg内においた方が良いでしょうか? 皆様のご意見をお聞かせください。

wotify に掲載されていた Hue のサンプルなど単独別リポジトリにあるものを参照しているのと、取りあえずどこかに置かなければならないので担当エンジニアの個人リポジトリにおいてリンクさせていますが、本リポジトリ内に置くべきであればそのようにもできます (ただ、随時ガンガンコードを入れていくのに PR 立ててマージというのは少し面倒なので落ち着いてから移行させる方が楽にはなります)。

**Comment by k-toumura** [comment]
myCobot 280(Python APIのWoT化)サンプル追加に関しては、#40 , #43 で完了していますので、一旦このissueはcloseさせていただきます。
