### ISSUE TITLE
CG内の意見、提案等の合意プロセスに関するドキュメントについて

### ISSUE THREAD

**Issue by chachamimm** [w3c/wot-jp-cg#37]
CG内の意見、提案等の合意を効率的に進めるために、下記の合意プロセスに関するドキュメントを作成しました。

[https://github.com/w3c/wot-jp-cg/blob/main/POLICY.md](url)

このドキュメントに関してご意見等がございましたら、ここに書き込んでください。

**Comment by KazuoKajimoto** [comment]
特に違和感ありません。

**Comment by chachamimm** [comment]
特に問題がないみたいなのですが、22日の会議でお話しした後に、採択ということでクローズします。

**Comment by dynamis** [comment]
こちらの issue をクローズできておりませんでしたが、22 日の会議後に "(Draft)" の記載を外しました。
-> closing
