### ISSUE TITLE
第1/2回 WoT-JP CG全体会議

### ISSUE THREAD

**Issue by chachamimm** [w3c/wot-jp-cg#39]
**タイトル**

第1回 WoT-JP CG全体会議

**概要**
- 基本的な方向
    - WoT-JP CGでの活動の方向性や、運営ポリシーについての説明
    - 参加者からの質疑応答
    - 想定会議時間は90分から120分くらい
    - 開催時期は2021年12月下旬か、2022年1月を予定
- Agenda案
     - 議長・司会: 水嶌
        1. WoTの現状とビジョン [芦村] (10分)
        2. CG設立の趣旨 [水嶌] (5分)
        3. 全体運営ポリシー [浅井] (5分)
        4. TF 活動紹介と作業手順 (40分)
            - Deployment [東村]
            - Outreach [安次富]
            -  Translation [芦村]
            - Use Cases [水嶌]
        5. Q&A (30分)
- その他
    - 上記のAgenda案以外で、Agendaとして取り上げ案があれば提案をしてください（このIssueにコメントしてください）

**目的**
- 少しずつ発起人を中心に有志で活動の方向性について議論をしてきていて、方向性が見えてきたので、一旦、その報告とCG参加者の皆様からの質問を受けるための会議を開くことにしました。
- いろいろ質問もあると思いますので、この機会にCG参加者の皆様とのコミュニケーションを取ることをしたいと思います。

**想定参加者**
- CG参加者
- CG参加者からの知り合いでCGの活動に興味がある人
- CGはW3C会員外からでも自由に参加できるので、あまり縛りは設けません

**想定実施時期**
- 2021年12月下旬か、2022年1月を予定
- 開催日は後で調整します

**Comment by dynamis** [comment]
note: 資料や当日の話のメモ (議事録というほどでは無い、私を含めた参加者によるリアルタイムメモ) についてはこちらのディレクトリに追加済:
https://github.com/w3c/wot-jp-cg/tree/main/Event/20211222_1st_Main_Meeting

**Comment by dynamis** [comment]
DONE! minutes はこの後で追加予定:
https://github.com/w3c/wot-jp-cg/tree/main/Event/20220128_2nd_Main_Meeting
