### ISSUE TITLE
イベント企画提案：出版業界向けWoT認知促進イベント

### ISSUE THREAD

**Issue by matsumotowataru47** [w3c/wot-jp-cg#44]
**タイトル**
出版業界向けWoT認知促進イベント 

**概要**
　・WoTについての概説（W3Cスタンダードとして／IoT・スマートテクノロジー利用環境の相互接続、共通技術プラットフォーム化可能技術標準／国内・海外WoT環境について／スマートシティ他）：芦村先生
　・WoT CG-Jについて、活動状況
　・出版業界での利用、事業可能性について：塩浜＋出版社／業界有志
　・今後の展開／出版業界とWoT関係者の結びつけ、WoT出版実装について：塩浜＋出版社／業界有志
　・Q&A

**目的**
目的：WoT認知促進、出版社／出版業界WoT展開推進、ユースケース創出契機
・出版業界に広くWoT認知を促す第一歩とする
・継続的WoT情報出版業界向け共有チャンネルの形成（上記業界団体会員＋ウェビナー参加者）
・出版社／業界有志（シンパサイザー）によるWoT出版展開のユースケース作り
・国内／海外WoT関係者とのネットワーキング化

**想定参加者**
・出版業界団体会員各社：APL-W3C慶應、電子出版社協会（デジタルコミック協議会）、電流協他

**想定実施時期**
* イベント開催：7/26（火）-29（金）のどこか
* 業界他開催告知：6/28（火）- 7/1（金）のどこか
  * 告知先：以下出版業界業界団体：APL、電書連、書協、電流協、出版社デジタル関係者（有力者に個別に）

**プログラム案**
* モデレータ：塩浜

* イベント説明 [塩浜]
* プレゼンテーション [芦村]
  * 5/18の日本会員会議資料(Smart Cities及びVoice)にもとづいて、WoTとは、産業展開、ユースケース、国内関係者の説明）
* 出版展開に関するパネル・ディスカッション：
  * 講談社、小学館、集英社、KADOKAWA、メディアドゥ有志（WoTシンパ）（１）出版コンテンツのWoT展開について、２）出版業界でのフォローアップ、ユースケースの創出
* Q&A

**イベント実施進行スケジュール案**
(要修正)
* 12月末までに：
  * イベント開催事務局確定（想定：MD-i塩浜／松本、WoT CG-J/OR-TFモデレーター？）
* 2022年1月：
  * 開催スケジュール調整、企画内容詰め、参加対象への働きかけ、協力の要請（業界団体会員各社への参加通知・促進等）
* 2月：
  * 開催スケジュール／企画実施案確定、出演者キャスティング＞芦村先生とウェビナープレゼンシナリオ調整中＞出版業界シンパサイザーと調整中
* 3月：
  * 事務局＋出演者＋業界有志ーイベント詳細調整、実施（必要時には4月開催の可能性あり）＞５月(or 6月）実施の方向で調整（４月のWoT別イベントと時間を開ける）
* 4月：
  * WoT CG-J／業界有志によるフォローアップ・ミーティング＞ユースケース策定に向けた継続活動案整理＞WoT戦略委員会／WoT-CG-Jへのフィードバック＞芦村先生とWoTユースケース、実例紹介を含め、業界シンパサイザーとの調整会議実施、出版コンテンツのWoT展開」についてシンパサイザーの認識を揃える
* 5月（or6月）：
  * ウェビナー実施＞フォローアップ業界シンパサイザー検討会議を継続展開し、四半期に一度業界内ユースケースを整理、WoT関係者＋出版業界内に進捗状況を共有する＞2022年秋ー冬に出版コンテンツ＋WoTユースケース実施を見込む

※注意:
* 開催日程を7月（中旬想定）に変更したく。6月中旬に告知（出版業界、WoT CG-Japan関係者他）可能なように調整を進める。
* 業界シンパサイザー検討会議を近日中に開催し、イベント内容についての検証を行う。
* イベント内でWoT認識を出版業界内で高めるだけでなく、出版WoTユースケース創出を実現する業界シンパサイザーを中心とした出版業界内継続的態勢を運営する。

**Comment by dajiaji** [comment]
@matsumotowataru47 松本さん、塩濱さんにgithubアカウント作成いただくようお願いいただけますでしょうか？

**Comment by dshiohama** [comment]
@dajiaji 塩浜です。githubアカウントでログインしています。すいませんが、上記のイベント企画案アップデートをしようとしているんですが、恥ずかしながら編集の書き込み方法が分からず、難儀しているところです。

**Comment by dajiaji** [comment]
@dshiohama 塩濱さん、イベント企画案の右上の「…」をクリック=>Editを選択、を試してみていただけますか？

**Comment by dshiohama** [comment]
> @dshiohama 塩濱さん、イベント企画案の右上の「…」をクリック=>Editを選択、を試してみていただけますか？

@dajiaji「…」を開けても「Edit」が出てこないんです。「Copy link, Quote reply, Report content」のメニューだけなんです。

**Comment by dynamis** [comment]
Edit メニューはリポジトリの権限がないと表示されないかと思います (他人の投稿を編集するには各リポジトリで権限が必要)。

ですので、権限がない場合は次のいずれかで対応が必要かと思います:
- 変更の差分について新しいコメントの中で記載する
- wot-jp-cg リポジトリの管理権限を持つ方 (@ashimura さんや @chachamimm さん？) に権限付与して貰ってから編集する

**Comment by dajiaji** [comment]
@dshiohama こちらにコメントとして書き込んでいただければ、私の方で、上記イベント企画案に反映させます。

浅井さんが書いてくださった以下の方針で。

> 変更の差分について新しいコメントの中で記載する

**Comment by matsumotowataru47** [comment]
> **タイトル** 出版業界向けWoT認知促進イベント
> 
> **概要** 　・WoTについての概説（W3Cスタンダードとして／IoT・スマートテクノロジー利用環境の相互接続、共通技術プラットフォーム化可能技術標準／国内・海外WoT環境について／スマートシティ他）：芦村先生 　・WoT CG-Jについて、活動状況 　・出版業界での利用、事業可能性について：塩浜＋出版社／業界有志 　・今後の展開／出版業界とWoT関係者の結びつけ、WoT出版実装について：塩浜＋出版社／業界有志 　・Q&A
> 
> **目的** ・出版業界に広くWoT認知を促す第一歩とする ・継続的WoT情報出版業界向け共有チャンネルの形成（上記業界団体会員＋ウェビナー参加者） ・出版社／業界有志（シンパサイザー）によるWoT出版展開のユースケース作り ・国内／海外WoT関係者とのネットワーキング化
> 
> **想定参加者** ・出版業界団体会員各社：APL-W3C慶應、電子出版社協会（デジタルコミック協議会）、電流協他
> 
> **想定実施時期** ・2022年3月（or4月）
> 
> **イベント実施進行スケジュール案** ・12月末までに：イベント開催事務局確定（想定：MD-i塩浜／松本、WoT CG-J/OR-TFモデレーター？） ・2022年1月：開催スケジュール調整、企画内容詰め、参加対象への働きかけ、協力の要請（業界団体会員各社への参加通知・促進等） ・2月：開催スケジュール／企画実施案確定、出演者キャスティング ・3月：事務局＋出演者＋業界有志ーイベント詳細調整、実施（必要時には4月開催の可能性あり） ・4月：WoT CG-J／業界有志によるフォローアップ・ミーティング＞ユースケース策定に向けた継続活動案整理＞WoT戦略委員会／WoT-CG-Jへのフィードバック

**Comment by ashimura** [comment]
@dajiaji さん, @dshiohama さんからメールでいただいた修正案です:
```
イベント実施進行スケジュール案
・12月末までに：イベント開催事務局確定（想定：MD-i塩浜／松本、WoT CG-J/OR-TFモデレーター？）
・2022年1月：開催スケジュール調整、企画内容詰め、参加対象への働きかけ、協力の要請（業界団体会員各社への参加通知・促進等）
・2月：開催スケジュール／企画実施案確定、出演者キャスティング＞芦村先生とウェビナープレゼンシナリオ調整中＞出版業界シンパサイザーと調整中
・3月：事務局＋出演者＋業界有志ーイベント詳細調整、実施（必要時には4月開催の可能性あり）＞５月(or 6月）実施の方向で調整（４月のWoT別イベントと時間を開ける）
・4月：WoT CG-J／業界有志によるフォローアップ・ミーティング＞ユースケース策定に向けた継続活動案整理＞WoT戦略委員会／WoT-CG-Jへのフィードバック＞芦村先生とWoTユースケース、実例紹介を含め、業界シンパサイザーとの調整会議実施、出版コンテンツのWoT展開」についてシンパサイザーの認識を揃える
・5月（or6月）：ウェビナー実施＞フォローアップ業界シンパサイザー検討会議を継続展開し、四半期に一度業界内ユースケースを整理、WoT関係者＋出版業界内に進捗状況を共有する＞2022年秋ー冬に出版コンテンツ＋WoTユースケース実施を見込む
```

お手数ですが，上記のセクションを差し替え願えませんでしょうか．

**Comment by dajiaji** [comment]
@dshiohama さん、@ashimura さん、 反応遅くなり申し訳ありません。差し替えました。

**Comment by ashimura** [comment]
@dajiaji さん，先ほど塩浜さんとご確認し，二つのアカウントが混同していたようですので，アカウントを整理いただきました．

今後は @dshioham を使ってコメントやご提案をいただく形です．

なお，不要な方のアカウントは削除いただきましたが，そうすると，GitHubのシステム上，「ghost」という名前に変更されちゃうようです．

**Comment by dajiaji** [comment]
芦村先生、了解いたしました。 @dshioham 塩濱さん、引き続き宜しくお願い致します。

**Comment by ashimura** [comment]
@dshioham さんからいただいたアップデートを企画案に反映．

**Comment by dajiaji** [comment]
@dshioham さん、 @ashimura さん、 @chachamimm さん、

前回定例で、あまりWoTに固執せず、出版業界の方々が興味を持ちそう、かつ、Web標準と出版の未来のつながりをイメージできそうな内容にしては？という話をしましたが、素案を投げておきます。

- タイトル（案）
  - W3C最新動向とデジタル出版の未来
  - 次世代デジタル出版に向けたW3C最新動向

- 概要（案）
  - W3Cは、2017年のIDPF(International Digital Publishing Forum)統合以降、デジタル出版のフォーマット規格(EPUB3)の策定・改訂を続けています。本イベントでは、EPUB3の最新動向に留まらず、次世代のデジタル出版に関係し得るW3Cの標準化動向について概観し、業界のキーパーソンを迎えてデジタル出版の未来についてディスカッションを行います。

- 動向として紹介する内容(案)
    - デジタル出版系メインストリーム最新動向: EPUB3 WG, Audiobooks WG
    - デジタル出版系の新しい動き：BD Comics Manga CG, Synchronized Multimedia for Publications CG
    - メタデータ・セマンティクス系： Web of Data & WoT
    - 将来系(メタバースとか未来を想起させるような？)： Media and Entertainment IG, Media WG, Immersive Web WG, WebXR Device WG

**Comment by dajiaji** [comment]
上記dajiajiのコメントのイベント案については、テレカンにて議論。

基本的に @ashimura がW3C全体説明の中で紹介いただくということでまとまった。イベントの内容自体は、WoTにフォーカスする従来の方向性を踏襲することとした。

**Comment by dynamis** [comment]
![image](https://user-images.githubusercontent.com/188166/193230648-0afa17c7-32b7-4fce-8ab0-8e66bf9d698b.png)
