### ISSUE TITLE
イベント企画提案：ECHONET Lite Web API と WoT

### ISSUE THREAD

**Issue by dajiaji** [w3c/wot-jp-cg#45]
**タイトル**
ECHONET Lite Web API と WoT

**概要**
現在、ECHONETコンソーシアムにてWeb API規格（ECHONET Lite Web API）の策定・改訂が進められている。
ELWAは、W3C WoTを参考にしているが準拠しているわけではない。
ECHONETコンソーシアムメンバに、WoT規格採用に至らなかった背景やWoTへの要望を伺い、
今後のW3C WoT規格拡張のヒントを得るとともに、将来的な ECHONETのWoT採用に可能性を探る。

**目的**
ECHONETからWoTへの要望をヒアリングし、WoTの次バージョンへ提案すべきユースケースや要求仕様の抽出を行うこと。

**想定参加者**
- ECHONETコンソーシアムメンバ
- W3C WoT WG/IG/CGの日本メンバ

**想定実施時期**
- 21年度内

**Comment by dajiaji** [comment]
2022年1月17日に、ECHONETコンソーシアム主査の寺本圭一殿（東芝）と打合せ。

結論から言うとイベントでの発表は了承いただいた。
- ただし、ECHONETコンソーシアムの月次定例会で承認を得なければならず、承認を得られるのが2月中旬。
- したがって、発表は2月下旬以降でお願いしたい
-  開催時間は平日17時以降でお願いしたい、とのこと
- 下記イベント内容についても了承頂いた。

内容：ECHONET Lite Web APIの概要説明 と W3C WoT規格準拠するための課題
- ECHONET Lite Web API (ELWA) は、Thing Descriptionを下敷きにしつつ、よりシンプルなクラウド上でRESTful APIを公開する前提の規格になっている。既に産業界で実際に採用されつつあり、今後も普及が見込まれる。このイベントでは、ECHONETコンソーシアム主査の寺本氏に、ELWAの概要とあわせて、W3C WoT規格準拠ではない理由（=採用に至らなかった課題）についても紹介いただき、参加者（WoT JP CGメンバ）間でディスカッションを行う。

その他：
- 普段芦村先生と話している内容は、ECHONETとWoTのゲートウェイにまつわる話であり、規格・仕様のSyncではない。
- 改めて規格の話をするのは意義がある。

**Comment by dynamis** [comment]
その後のやり取り踏まえて、イベント案内・募集案を事務局にて用意致しました:
https://github.com/wot-jp-community/all/blob/main/planning/StudyMeeting/20220228/information.md

皆様確認、コメント頂いた上で確定できれば幸いです。

**Comment by dynamis** [comment]
todo:
- [ ] 日程を確定する (3/11 17:00-19:00 を想定中) 
- [ ] 開催概要に主催者として ECHONET / WoT CG を記載するか
  - 現状公式サイトという形で書いているが、主催者として記載した上で公式サイトにリンクしておく形で良いのではないか
- [ ] WoT を前面に出すべきか ECHONET を前面に出すべきか
  - タイトルや説明の仕方に反映する
  - 時間割りで ECHONET と WoT いずれのセッションを先にすべきかにも影響する
- [ ] 時間割りを確定する
  - セッションの枠、タイトル、時間、講演者
- [ ] 想定参加者 / ターゲット層を明確にする/追記する
- [ ] イベントツールをどうするか決める (connpass で良いのか、もっと企業向けの雰囲気のあるものにすべきか)
- その他

**Comment by chachamimm** [comment]
イベントの立ち位置として、WoT-JP CGが主体で、ECHONETの方を招待して講演を行うというスタイルの方がわかりやすいと思います。

どういうイベントをするのかというシナリオも必要だと思います。

想定参加者は、どういうシナリオでこのイベントを行うのか次第だと思います。企業向けなのか、個人向けなのかで講演される方も内容が変わってくるのではないかと思います。その辺りは早めに決めて、後援者にも説明しておく必要があると思います。

私からの希望としては、単純にECHONET-liteの技術的な話をしてもらうのではなく、ユースケースに基づいてECHONET-liteの利点と問題点を考えて、WoTとの連携を考えるという感じのができればと思っています。出てきたユースケースは後で、ユースケースの１例とすることもできるのではないかと思います。

**Comment by dynamis** [comment]
WoT CG主催、主体でECHONETコンソーシアムは後援なり協賛なり。

ターゲットはWoTやECHONET Lite Web API の採用検討、あるいは IoT デバイス開発に関心のある企業および個人でもこれらの技術の学習と研究をされたい方

ECHONETセッションの後半にWoTとの連携の可能性についてもお話しいただき、それを踏まえて登壇者もしくはそれに1-2名加えたスピーカーでディスカッションするトークセッションをして締めると良さそうですね。

**Comment by dajiaji** [comment]
@chachamimm 反応遅れました。コメントありがとうございます。

> どういうイベントをするのかというシナリオも必要だと思います。
> 想定参加者は、どういうシナリオでこのイベントを行うのか次第だと思います。

ECHONET Lite Web API（ELWA）パートに関しては、本Issueの冒頭に「目的：ECHONETからWoTへの要望をヒアリングし、WoTの次バージョンへ提案すべきユースケースや要求仕様の抽出を行うこと。」と書いているとおり、主要な想定参加者は、W3C WoT 関係者です。ELWAの発表者にも、① ELWAでWoT準拠に至らなかった理由、 ② WoTで規定されていないELWA独自の機能の紹介、を盛り込んで頂くようお願いしています。

> 単純にECHONET-liteの技術的な話をしてもらうのではなく、ユースケースに基づいてECHONET-liteの利点と問題点を考えて、WoTとの連携を考えるという感じのができれば

ということで、①②をネタに発表後に質疑ができれば、水嶌さんの要望はある程度満たされるのではないかと思っています。

W3C WoTの紹介（実装面含む）とのジョイントとすることで、想定参加者に、 @dynamis が書いてくださっているように、（W3C と ELWAを含む広い意味での）WoT標準規格の最新動向やこれらの規格準拠のIoTデバイス開発に興味のある団体・個人が加わるイメージです。
