### ISSUE TITLE
SwitchBotサンプル追加の提案

### ISSUE THREAD

**Issue by hidessy** [w3c/wot-jp-cg#50]
コンテンツの拡充に向けて、SwitchBotサンプルを追加したいと考えています。
内容やツールに関しては、Hueのサンプルと同様の流れで、Thing Descriptionを元に、Node-REDからnode-red-nodegenを使って、まとめていきたいと思います。
SwitchBotのサンプルですが、Hueのサンプルで電球は既に取り上げていますので、まずは開閉センサーを使ったものを作成したいと考えています。
後ほど、Pull Requestとしての提案をさせていただきます。
よろしくお願いいたします。

**Comment by k-toumura** [comment]
#51 がマージされましたので、closeいたします。
