### ISSUE TITLE
WoT 構成要素の全体像が分かる説明と作図をする

### ISSUE THREAD

**Issue by dynamis** [w3c/wot-jp-cg#56]
WoT とはなんのためにあるのかといったレベルの概要は /about に書き足されてきたが、具体的に WoT の構成要素やそれらの関係、外部仕様や外部標準との関係性がより理解しやすいように作図と説明の追加をしたい。

場所としては /about ページに追記するのか /rec ページの冒頭に入れるのかあるいは少しずつ違う図を用意して両方で説明するのか迷うが、まずは WoT の構成・役割・何をどう定義してるか分かるような図が欲しい。

既存の比較的分かりやすい図:

IETF で使われた資料内で Building Block 図を書いてるのが全体像としては分かり易い:
https://www.ietf.org/proceedings/interim-2017-t2trg-02/slides/slides-interim-2017-t2trg-02-sessa-05-w3c-wot-00.pdf
![image](https://user-images.githubusercontent.com/188166/151788159-27edae7a-fbf1-4511-be6e-797f8cdcbd2a.png)

各仕様と依存する標準仕様との関係性が分かる:
https://commons.wikimedia.org/wiki/File:WoT_Thing_Description_Components.png
![image](https://user-images.githubusercontent.com/188166/151788216-b567bf84-fc34-41f7-8b73-42735fb90951.png)

モノと TD に記述される内容の対応関係がある程度分かる:
https://www.w3.org/TR/wot-architecture/
![image](https://user-images.githubusercontent.com/188166/151788312-f09a5b14-107e-4ff0-b832-104664e61ad5.png)
![image](https://user-images.githubusercontent.com/188166/151788337-a68d728c-17c6-4d08-9f5b-7f4914e5c3ea.png)

**Comment by dynamis** [comment]
私なりに整理して 1 枚にまとめてみた例:
![WoT Building Blocks](https://user-images.githubusercontent.com/188166/151788783-b0ab375f-caae-4258-8b0d-2238c4f0e143.png)

**Comment by dynamis** [comment]
@ashimura @chachamimm @k-toumura WoT についてこれから学ぶ人に WoT 構成要素 (構成仕様と役割) がの全体像を説明するのに、どのような図を用意すると良いか、既存の良い図があったり上の図をどう修正したら良いか、そもそも間違ってる/誤解を招くところがないかなどアドバイスいただけないでしょうか。

**Comment by hidessy** [comment]
お世話になっております。
/about または /recs ページで、上記のようなBuilding Block図の前に、まずは、WoT仕様が8個あること及び、それらの仕様の関係を簡単に理解するために、下図のような感じで図示することが出来ないかと考えています。

![architecture](https://user-images.githubusercontent.com/65905334/151811605-5e4363cd-cb5b-4972-9a4a-4cada7dcd78b.svg)

しかし、Profileの位置であったり、8つの仕様だけを1つの図に出来るのか、どのようにすべきなのかがわからないため、ご教授いただけないでしょうか。
よろしくお願いいたします。

**Comment by dynamis** [comment]
綺麗に整理しきれてないが @hidessy の書いて頂いた仕様関係図について芦村さんからのフィードバックをその場でメモったモノを貼り付けます:

- 大筋の内容については間違いないが、時系列が欠落している点が気になる
- 時系列とドキュメント間の関係性が一連に関わりある事ではない点が複雑にしている
    - 時系列ではなく関係性という意味では大きな齟齬はない
- use case が始点となり、normative 4 仕様を作る
    - arch, td, discovery, profile を作っていく
    - binding / scripting は
    - security / privacy は土台というよりは垂直に横から背骨が支える感じにした方が良いかも
- normative なのは 4 つ
    - arch, td, discovery
    - binding template は mozilla/google から反対があり、格下げになった。優先度の問題はあるが作る上では必要な語彙の仕様
        - 本来 http/mqtt/coap などのプロトコル固有はレジストリとして登録・管理して増やしていけるようになるべきだろう
- scripting は td を js 環境から操作するための api
- binding は産業用用の CoAP などのプロトコルとのマッピングを行う
- profile の位置づけはまだ未確定なところがある
    - core profile
        - もともと embedded など小さいデバイス向けと想定して書き始められたが、標準化メンバー間で意識が統一されていない。
        - あくまでも基本を決めているモノという考え方もある
    - 図の中の書き方はまだどうするべきか決めかねる。一旦図としては書かない形にしておくのもありかもしれない。

**Comment by hidessy** [comment]
フィードバックありがとうございます。
頂いたコメントをもとに仕様書の関係を修正したものになります。
profileに関しては、薄く付け加えています。
ご確認よろしくお願いいたします。

![architecture](https://user-images.githubusercontent.com/65905334/153818960-07e1e584-e132-49c5-ae78-9bccbc5f53ff.png)

**Comment by k-toumura** [comment]
Use Cases ... と Security ... が土台や横の柱として他の文書を支えるという意味でUse Cases ...とSecurity ...から出ている矢印はわかりますが、
- Binding ...がTDを支えているわけではないし、派生させているわけでもない
- DiscoveryとScripting APIがProfile, TD, Binding...を支えているわけではないし、派生させているわけでもない

のでこれらから出ている矢印は削除するか別のスタイルにすべきかと思います。

Profileの位置づけとしては、TD, Binding..., Discoveryの中の典型的実装パターンを選んで1つのプロファイルとすることを考えると、TD, Binding..., Discovery, (間接的にSecurity)から矢印がでてProfileに向かう、という図になるのかもしれません。
(Scriptingは今のところProfile内での言及はないですが、「このScriptint APIが実装されたConsumer」といったprofileを将来作ることはできると思われます。)

PRに含まれていたファイルを編集したものを案として下記に置きます(SVGなのでinkscapeで読み込めます)
![architecture](https://user-images.githubusercontent.com/30313213/156956530-9579d655-f93f-46d9-92ea-dfd575595d71.svg)

**Comment by hidessy** [comment]
図の修正・作図、ありがとうございます。
プルリク #62 の方に反映いたしました。
よろしくお願いいたします。

**Comment by dynamis** [comment]
サイトに掲載したものは完了済＆勉強会のスライドで使うものも完了済。
