### ISSUE TITLE
イベント企画提案：WoTユースケース全般を概観する勉強会

### ISSUE THREAD

**Issue by ashimura** [w3c/wot-jp-cg#67]
**タイトル**
オープン標準による IoT の世界 - 具体的ユースケースを踏まえて

**概要**
W3C Web of Things（WoT）は、Web技術を用いてIoTプラットフォーム間の相互運用を実現するための標準技術であり、Web of Things Japanese Community Group (WoT-JP CG)では、我が国でのWoT標準の普及促進を図るため、多くの業界関係者を交えて様々な議論や活動に取り組んでいる。

一方、W3C Web of Things Working GroupおよびInterest Group (WoT-WG/IG) では、今日までに、WoT標準の様々な産業への応用事例 (ユースケース) および技術要件 (リクワイアメント) が集約され、WoT Use Cases and Requirements Note (ユースケース文書) として文書化されている。

今回の勉強会では、[最新版のユースケース文書](https://www.w3.org/TR/2022/NOTE-wot-usecases-20220307/) が2022年3月7日に公開されたことを受けて、あらためて、ユースケース文書中の産業応用事例を全般的にご紹介するとともに、ユースケース文書にはまだ記載されていない、WoTのIoT応用事例についてご紹介した上で、今後のユースケース検討の方向性や、WoTの将来展望について意見交換する。

**目的**
WoT標準化作業の現状、および今までのユースケース議論について概観した上で、
IoT エンジニア、メーカー、サービスベンダー等、業界ステークホルダーの方と、
WoTの産業応用に関して広く情報共有するとともに、将来的な応用先の可能性について意見交換する．

**想定参加者**
* IoT 開発に関わるエンジニア
* 標準化技術を活用する、あるいはこれから活用していくエンジニア、メーカー、サービスベンダーの方
* その他、IoTへの Web活用全般に興味のある方

**想定実施時期**
* 2022年3月末 (3/22, 23, 24, もしくは25; 第一候補は3/25(金))
* 時間は社会人の方が参加しやすいよう 17:00-19:00を想定

**Comment by dynamis** [comment]
> [最新版のユースケース文書](https://www.w3.org/TR/2022/NOTE-wot-usecases-20220307/) が2022年3月7日に公開されたことを受けて

おぉ、最新の世界の議論が聞けるという雰囲気で良いタイミング！

**Comment by dynamis** [comment]
こちらに書き残し忘れていたが、connpass で募集開始や本リポジトリにイベント概要 md ファイルを作成済み:

https://wot-jp-cg.connpass.com/event/242456/
https://github.com/w3c/wot-jp-cg/tree/main/Event/20220325_4th_WoT_Usecases_Event

残タスクとしては多分これくらい:
- [ ] 準備完了 (予行演習)
- [ ] 実施
- [ ] ノートの作成
- [ ] 発表資料 PDF のリポジトリへの公開
- [ ] 資料公開のご案内
