### ISSUE TITLE
イベント開催/運営メモを用意する

### ISSUE THREAD

**Issue by dynamis** [w3c/wot-jp-cg#73]
[connpass wot-jp-cg](https://wot-jp-cg.connpass.com/) でイベント告知から終了後のフォローアップまでの手順・参考メモを用意する。

想定は https://github.com/w3c/wot-jp-cg/tree/main/TF/Outreach 配下に適当な md ファイルで以下の点を簡単に書き残す:

- [ ] connpass イベント作成の注意
  - [ ] ハッシュタグを設定する (#wotjp ? #wotjpcg ? #wot-jp ? ...)
  - [ ] 申し込み期日は開催直前 (前日当日応募も多い)
  - [ ] github の event ディレクトリ配下の readme.md との相互リンクする
- [ ] 参加登録時アンケートのテンプレ
- [ ] イベント終了後対応
  - [ ] 講演 PDF を集めて github & connpass に追加
  - [ ] conpass でのフォローアップメールテンプレ

**Comment by Aritaka-hub** [comment]
イベント終了後対応で、connpass でのフォローアップメールのテンプレ案です。
※WoT＆ELWA勉強会の終了後は以下の内容でメール送付しております。
追加でこうした方が良い、と言う案があればテンプレにご提案願います。

```
件名：[開催日] 開催、[イベント名] にご参加いただきありがとうございました。

内容：
[イベント名] へご参加いただきありがとうございました。

当日の資料は、講演の中でご紹介いただいた W3C WoT-JP CG の GitHub で公開しております。
以下の URL または、connpass の資料からリンクを張っておりますので、興味をお持ちの方はダウンロードをお願いします。
[資料へのURL：GitHub]

また、本日の講演で質問をお持ちの方からの問い合わせ、 CG活動に興味を持たれた方の参加を歓迎いたします。
下記の GitHub issues や メール宛で WoT-JP CG にご連絡ください。

GitHub：https://github.com/w3c/wot-jp-cg/issues/new/choose
Mali：public-wot-jp@w3.org

どうぞよろしくお願い致します。


以上
```

**Comment by Aritaka-hub** [comment]
#75 にて、connpass 募集の編集方法について記事化しました。
過去のイベントの再利用が可能な物についての更新手段になります。

**Comment by dynamis** [comment]
運営メモじゃないけど connpass 関連の設定チェックリスト:

- グループのロゴは先日適当に WoT 公式ロゴ？を入れました
- [ ] カバー画像が未設定
ォルトのままになっている。何か WoT っぽいものを入れておきたい
- [ ] グループの名前だけ設定されサブタイトルや主催の設定はない
  - 主催者というかグループ名がそのままグループ名だから要らないとも言う
- [ ] グループの説明に github へのリンクや質問受け付けてるよという記載が欲しい
- リンクはそれっぽいものをいくつか設定しておいた

**Comment by dynamis** [comment]
細かな改善点はまだあるが、一旦イベント開催/運営メモを作って引き継ぎすることは完了済なのでクローズします。
