### ISSUE TITLE
イベント企画提案：ユースケース検討会

### ISSUE THREAD

**Issue by dajiaji** [w3c/wot-jp-cg#85]
**タイトル**
WoTユースケース検討会

**概要**
これまで開催してきた具体的な応用領域を対象としたイベント（ ECHONETLite Web APIやビル）の中で、WoTへの要望に近い話題が幾つか挙がった。一度、有志でこれまでのイベントのテーマを題材としたユースケース造出会を実施したい。

**目的**
- WoT 2.0に向けた新規ユースケースの造出。
- これまでのイベントで上がった応用領域における潜在的な機能要求・非機能要求の抽出。

**想定参加者**
- これまでのイベント参加者
- W3C WoT JP CGメンバ

**想定実施時期**
- 2022年6月

**Comment by ashimura** [comment]
#91 とマージする方向で，本Issue自体はクローズする．
